service: esri-etl

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 6

  stage: ${opt:stage, self:custom.defaultStage}
  envVarsFile: ${opt:envdir, '.'}/${self:provider.stage}-vars.yml
  region: us-west-2

  vpc: ${file(${self:provider.envVarsFile}):vpc}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - KMS:Decrypt
      Resource: ${file(${self:provider.envVarsFile}):kmskey}

  environment: ${file(${self:provider.envVarsFile}):environment}
  environmentSecrets:
      PGPASSWORD: '/scout/${self:provider.stage}/pgpassword'

functions:
  - ${file(./serverless-config/interra-group-avl-functions.yml)}
  - ${file(./serverless-config/chulavista-avl-functions.yml)}

plugins:
  - serverless-secrets

custom:
  defaultStage: dev
